name: nodejs_workflow
on: workflow_dispatch
jobs:
   jobs1:
     runs-on: ubuntu-latest
     steps: 
       - name: checkout cloaning
         uses:  actions/checkout@v4
       - name: install nodejs
         uses: actions/setup-node@v4
         with:
          node-version: 18
          cache: 'npm'
   jobs2:
      runs-on: ubuntu-24.04
      steps:
        - name: Install dependencies
          run: npm ci
        - name: Executes test cases
          run: npm test
        - name: Build the code
          run: npm run build
        - name: Deploy the code
          run: echo 'Deploy the code'
     
