name: nodejs workflow
on: workflow_dispatch
jobs:
  job1:
    run-on: ubuntu-latest
    steps: 
    - name: clone repo
      uses: actions/checkout@v4.2.2
    - name: install nodejs
      uses: actions/setup-node@v4
      with:
          node-version: 18
          cache: 'npm'
    - name: install dependines
      run: npm ci
    - name: test case
      run: npm test
      
